// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOU9Knlb8iNih7rIgPeZW_r6BmFLgekfQ',
    appId: '1:659627636777:web:222a0bf250659667464438',
    messagingSenderId: '659627636777',
    projectId: 'test-17b4e',
    authDomain: 'test-17b4e.firebaseapp.com',
    storageBucket: 'test-17b4e.appspot.com',
    measurementId: 'G-CYCSLYB9DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEcZAy8hab2LAnalgkz7B6pt_Td2bSN8s',
    appId: '1:659627636777:android:1b3483e25ee83eaf464438',
    messagingSenderId: '659627636777',
    projectId: 'test-17b4e',
    storageBucket: 'test-17b4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjqZEGW0WMUuEQ3nzTkoM-45FTOjYiVP4',
    appId: '1:659627636777:ios:4a5ed48109d52550464438',
    messagingSenderId: '659627636777',
    projectId: 'test-17b4e',
    storageBucket: 'test-17b4e.appspot.com',
    iosClientId: '659627636777-nmismrstop0o0o8d9gjfnnu5bolu0k93.apps.googleusercontent.com',
    iosBundleId: 'com.example.namtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjqZEGW0WMUuEQ3nzTkoM-45FTOjYiVP4',
    appId: '1:659627636777:ios:04812b4ba70659b2464438',
    messagingSenderId: '659627636777',
    projectId: 'test-17b4e',
    storageBucket: 'test-17b4e.appspot.com',
    iosClientId: '659627636777-03j2c2t85u5ptp8rgatmhimk1f3fd0nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.namtest.RunnerTests',
  );
}
